### ISSUE TITLE
How to replace the emoji beside projects

### ISSUE THREAD

**Issue by dnmanveet** [naye0ng/Grape-Theme#10]
On the blog posts page. I enabled the option of displaying the projects. But, I am also getting an emoji of a girl with a raising hand. How do I replace that or even remove that. Below is the screen shot for your reference
![Screenshot from 2020-04-27 11-14-04](https://user-images.githubusercontent.com/29728855/80337998-e81eb100-8878-11ea-8f20-8355d8db585c.png)

**Comment by TanZng** [comment]
You can change them on `_includes/projects.html` and on `_includes/aside.html` :octocat:

**Comment by dnmanveet** [comment]
Thank you @TanZng . Sorted it out.
