### ISSUE TITLE
Content overflow issue in code block

### ISSUE THREAD

**Issue by jeonyeohun** [naye0ng/Grape-Theme#14]
안녕하세요? 잘 만들어주신 Jekyll Theme 을 사용하고 있는 사용자입니다. 

사용하던 중 글의 길이가 길어져 code block의 가로 길이를 넘어갈 경우 문자들이 clip 되어 확인을 할 수 없는 issue 가 있는 것을 발견하였습니다. 저는 `_hightlight.scss` 에 overflow 속성을 추가하여 사용하고 있습니다. 혹시 도움이 될까 싶어 이슈드립니다. 좋은 테마자료를 만들어주셔서 감사합니다!

~~~
.highlight pre {
    padding: 10px;
    margin: 10px 0;

    * {
        font-size: 0.9rem;
    }
    overflow: scroll;
}
~~~

**Comment by naye0ng** [comment]
안녕하세요.
해당 이슈는 현재 해결되었습니다.
관심 가져주셔서 감사합니다.😊

[Issue #13](https://github.com/naye0ng/Grape-Theme/pull/13)
