### ISSUE TITLE
Cant set the image to its original size in a Blog post(fully blurred and Enlarged)

### ISSUE THREAD

**Issue by dnmanveet** [naye0ng/Grape-Theme#7]
I love to reviewing books i read. I also like to post the front cover of the book and then write review below that. But, the image appears to be so large and fully blurred and cant be assign it a size or width and cant even leave it to its original size.
For reference: 
https://dnmanveet.github.io/ (every post will have at least one picture)
https://dnmanveet.github.io/novels/2019/08/02/You-are-the-best-friend.html
https://dnmanveet.github.io/novels/2019/05/12/You-Are-The-best-wife.html

**Comment by naye0ng** [comment]
I added CSS class to adjust image width.
After pull the master branch, refer to the [description](https://grape-theme.netlify.app/2019/06/08/markdown-and-html.html).

```
![sample image](/assets/img/koreaSunset.jpg){: .width-50}
```

**Comment by dnmanveet** [comment]
Yes, thanks.
